apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wikijs.deployName" . }}
spec:
  replicas: {{ .Values.replicas | default 3  }}
  selector:
    matchLabels:
      app: {{ include "wikijs.deployName" . }}
  template:
    metadata:
      labels:
        app: {{ include "wikijs.deployName" . }}
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki:{{ .Values.version }}
          resources: {}
          env:
            - name: DB_TYPE
              value: {{ .Values.database.type | default "mariadb" }}
            - name: DB_HOST
              value: {{ .Values.database.host }}
            - name: DB_PORT
              value: {{ .Values.database.port | default "3306" | quote }}
            - name: DB_USER
              value: {{ .Values.database.user | default "wikijs" }}
            - name: DB_PASS
              value: {{ .Values.database.password | default "wikijs" | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | default "wikijs" }}
          ports:
            - name: web
              containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30