apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wikijs.ingName" . }}
  labels:
    app.kubernetes.io/name: {{ include "wikijs.ingName" . }}
spec:
  {{- if .Values.ingress.tls.secretName }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.host }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "wikijs.svcName" . }}
            port: 
              number: 3000
