apiVersion: v1
kind: Pod
metadata:
  name: {{ printf "debug-pod-%s" .Release.Name }}
spec:
  containers:
    - name: debug-pod
      image: deejayadi/debug-pod:{{ .Chart.AppVersion }}
      command:
        - /bin/bash
        - -c
      args:
        - sleep infinity
      resources: {}
