apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.secret" . }}
type: Opaque
data:
  # Encryption Key
  N8N_ENCRYPTION_KEY: {{ .Values.n8n.encryption_key | b64enc | quote }}
  {{- if eq (.Values.db.type | default "sqlite") "postgresdb" }}
  # Database Credentials
  DB_POSTGRESDB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.email.enabled }}
  # Email Credentials
  N8N_SMTP_USER: {{ .Values.email.user | b64enc | quote }}
  N8N_SMTP_PASSWORD: {{ .Values.email.password | b64enc | quote }}
  {{- end }}