apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.svcName" . }}
spec:
  selector:
    app: {{ include "n8n.deployName" . }}
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.n8n.port }}
      targetPort: {{ .Values.n8n.port }}
      protocol: TCP