replicas: 1
version: 2.5

database:
  type: "sqlite" # sqlite | mysql | postgres | mariadb | mssql
  host: "" # Default: ""
  port: "3306" # Default: "3306"
  user: "wikijs" # Default: wikijs
  password: "wikijs" # Default: wikijs
  name: "wikjs" # Default: wikijs

service:
  type: ClusterIP

ingress:
  host: "wikijs.lab.home.arpa" # Default: "wikijs.lab.home.arpa"
  tls:
    secretName: "" # Default: ""
