apiVersion: v1
kind: Secret
metadata:
  name: cf-tunnel-secret
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  token: {{ .Values.config.token | b64enc }}
